# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20170614_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'high'), (2, 'medium'), (3, 'normal'), (4, 'low')]),
        ),
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'high'), (2, 'medium'), (3, 'normal'), (4, 'low')]),
        ),
    ]
